PRAGMA foreign_keys = ON;

CREATE TABLE Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    Role TEXT NOT NULL CHECK(Role IN ('Admin','User'))
);

CREATE TABLE Workouts (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Date TEXT NOT NULL,
    Duration INTEGER NOT NULL,
    UserId INTEGER NOT NULL,
    FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Exercises (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE,
    MuscleGroup TEXT NOT NULL
);

CREATE TABLE ExerciseLogs (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    WorkoutId INTEGER NOT NULL,
    ExerciseId INTEGER NOT NULL,
    Sets INTEGER NOT NULL,
    Reps INTEGER NOT NULL,
    Weight REAL NOT NULL,
    FOREIGN KEY(WorkoutId) REFERENCES Workouts(Id) ON DELETE CASCADE,
    FOREIGN KEY(ExerciseId) REFERENCES Exercises(Id) ON DELETE CASCADE
);

CREATE TABLE Progress (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    Date TEXT NOT NULL,
    Weight REAL NOT NULL,
    FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
